# Generated by Django 3.1.4 on 2020-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(default=None, help_text='AppID/ClientID that will be used to perform eBay API requests.', max_length=40, unique=True, verbose_name='AppID/ClientID')),
                ('is_primary', models.BooleanField(default=False, help_text='Only one credential can be primary at same time', verbose_name='Primary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ebay_id', models.BigIntegerField(verbose_name='eBay Item ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.TextField(help_text='May contain HTML tags.', verbose_name='Description')),
                ('location', models.CharField(max_length=45, verbose_name='Location')),
                ('condition', models.CharField(max_length=32, verbose_name='Condition')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price in USD')),
                ('url', models.URLField(verbose_name='URL')),
                ('hash', models.CharField(editable=False, help_text='Hash that allows to check if product was changed from last update.', max_length=32, verbose_name='Hash')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
