# Generated by Django 3.1.4 on 2020-12-13 19:10

from django.db import migrations, models
import django.db.models.deletion
import ebay.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='app_id',
            field=models.CharField(default=None, help_text='AppID/ClientID that will be used to perform eBay API requests. Max. length 40 characters.', max_length=40, unique=True, verbose_name='AppID/ClientID'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Only one credential can be primary at same time.', verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(help_text='Max. length 32 characters.', max_length=32, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebay_id',
            field=models.BigIntegerField(help_text='eBay Item ID from API', verbose_name='eBay Item ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(help_text='Max. length 45 characters.', max_length=45, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='All prices are in USD currency.', max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Max. length 80 characters.', max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(help_text='Product URL on eBay', verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(help_text='Product image from eBay item.', upload_to=ebay.models.product_image_upload_path, verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, help_text='Only one image can be primary at same time.', verbose_name='Primary')),
                ('product', models.ForeignKey(help_text='eBay product.', on_delete=django.db.models.deletion.CASCADE, to='ebay.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
