# Generated by Django 3.1.4 on 2020-12-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebay', '0002_auto_20201213_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(help_text='Max. length 255 characters.', max_length=255, verbose_name='Search keyword')),
                ('hash', models.CharField(editable=False, help_text='Hash that allows to check if searhc results were changed from last update.', max_length=32, verbose_name='Hash')),
                ('owner', models.ForeignKey(help_text='Search request initiator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
