# Generated by Django 3.1.4 on 2020-12-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.ForeignKey(default=1, help_text='Search request keyword', on_delete=django.db.models.deletion.CASCADE, to='ebay.search', verbose_name='Search request'),
            preserve_default=False,
        ),
    ]
