# Generated by Django 3.1.4 on 2021-01-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0005_auto_20210113_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='session',
            field=models.UUIDField(default=None, editable=False, help_text='Used to determine search query session.', null=True, verbose_name='Session UUID'),
        ),
        migrations.AlterField(
            model_name='search',
            name='hash',
            field=models.CharField(editable=False, help_text='Hash that allows to check if search results were changed from last update.', max_length=32, verbose_name='Hash'),
        ),
    ]
