# Generated by Django 3.1.4 on 2021-01-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0006_auto_20210120_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(help_text='Product thumbnail URL on eBay', null=True, verbose_name='Thumbnail URL'),
        ),
    ]
