# Generated by Django 3.1.4 on 2021-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0007_product_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_it_now',
            field=models.BooleanField(default=False, help_text='Determines that product is available for buy it now option.', verbose_name='Is but it now'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(help_text='ISO 3166 country code. Max. length 2 characters.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_rated_seller',
            field=models.BooleanField(default=False, help_text='Determines that seller is top rated within eBay.', verbose_name='Is top rated seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(help_text='Product thumbnail URL on eBay.', null=True, verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(help_text='Product URL on eBay.', verbose_name='URL'),
        ),
    ]
