# Generated by Django 3.1.4 on 2021-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0008_auto_20210203_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='cert_id',
            field=models.CharField(blank=True, default=None, help_text='CertID that will be used to perform eBay API requests. Max. length 40 characters.', max_length=40, null=True, unique=True, verbose_name='CertID'),
        ),
    ]
