# Generated by Django 3.1.4 on 2021-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0009_credential_cert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(help_text='Product URL on eBay.', max_length=300, verbose_name='URL'),
        ),
    ]
