# Generated by Django 3.1.4 on 2021-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0011_product_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='May contain HTML tags.', null=True, verbose_name='Description'),
        ),
    ]
