# Generated by Django 3.1.4 on 2021-03-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0012_auto_20210302_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_type',
        ),
    ]
