# Generated by Django 3.1.4 on 2021-03-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0013_remove_product_brand_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the Brand Type filter.', max_length=255, verbose_name='Name')),
                ('active_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Brand Type',
                'verbose_name_plural': 'Brand Types',
            },
        ),
    ]
