# Generated by Django 3.1.4 on 2021-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0014_brandtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='api_limit_mtime',
            field=models.DateTimeField(blank=True, help_text='Time when api limit was expired', null=True, verbose_name='ApiLimitMTime'),
        ),
        migrations.AddField(
            model_name='credential',
            name='query_count',
            field=models.IntegerField(default=0, help_text='Count query to the ebay with these credentials per dey', verbose_name='QueryCount'),
        ),
    ]
