# Generated by Django 3.1.4 on 2021-03-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0015_auto_20210306_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(help_text='Username of the product seller', max_length=255, verbose_name='Seller')),
                ('feedback_percentage', models.DecimalField(blank=True, decimal_places=1, help_text='Feedback percentage of the product seller', max_digits=4, null=True, verbose_name='Feedback Percentage')),
                ('feedback_score', models.IntegerField(blank=True, help_text='Feedback score of the product seller', null=True, verbose_name='Feedback Score')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller of the product', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay.seller', verbose_name='Seller'),
        ),
    ]
