# Generated by Django 3.1.4 on 2021-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0016_auto_20210310_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='brand_types',
            field=models.CharField(blank=True, help_text='Max. length 1000 characters', max_length=1000, null=True, verbose_name='Brand Types'),
        ),
        migrations.AddField(
            model_name='search',
            name='compatibility',
            field=models.CharField(blank=True, help_text='Max. length 1000 characters', max_length=1000, null=True, verbose_name='Compatibility'),
        ),
        migrations.AddField(
            model_name='search',
            name='max_delivery_cost',
            field=models.BooleanField(blank=True, help_text='False if free shipping', null=True, verbose_name='Max Delivery Cost'),
        ),
    ]
