# Generated by Django 3.1.4 on 2021-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0017_auto_20210316_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='conditions',
            field=models.CharField(blank=True, help_text='Max. length 1000 characters', max_length=1000, null=True, verbose_name='Conditions'),
        ),
    ]
