# Generated by Django 3.1.4 on 2021-03-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0018_search_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search',
        ),
        migrations.CreateModel(
            name='SearchProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Many to one relations with Product table', on_delete=django.db.models.deletion.CASCADE, related_name='search_product', to='ebay.product', verbose_name='Product')),
                ('search', models.ForeignKey(help_text='Many to one relations with Search table', on_delete=django.db.models.deletion.CASCADE, related_name='search_product', to='ebay.search', verbose_name='Search')),
            ],
            options={
                'verbose_name': 'Search Product',
                'verbose_name_plural': 'Search Product',
            },
        ),
    ]
