# Generated by Django 3.1.4 on 2021-06-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0020_auto_20210615_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
