# Generated by Django 3.1.4 on 2021-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0022_auto_20210615_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Max. length 80 characters.', max_length=80, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(help_text='Max. length 80 characters.', max_length=80, null=True, verbose_name='Part number'),
        ),
    ]
