# Generated by Django 3.1.4 on 2021-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0024_auto_20210622_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchindex',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.AddField(
            model_name='searchindex',
            name='top_product',
            field=models.ManyToManyField(to='ebay.Product'),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='vendors',
            field=models.ManyToManyField(to='ebay.Vendor'),
        ),
    ]
