# Generated by Django 3.1.4 on 2021-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0025_auto_20210701_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='top_product',
            field=models.ManyToManyField(blank=True, to='ebay.Product'),
        ),
        migrations.AlterField(
            model_name='searchindex',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='ebay.Vendor'),
        ),
    ]
