# Generated by Django 3.1.4 on 2021-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0026_auto_20210701_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='keywords',
            field=models.CharField(help_text='Max. length 255 characters.', max_length=255, unique=True, verbose_name='Search index keyword'),
        ),
    ]
