# Generated by Django 3.1.4 on 2022-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0027_auto_20210701_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='keywords',
            field=models.CharField(help_text='Max. length 255 characters.', max_length=255, verbose_name='Search index keyword'),
        ),
    ]
