# Generated by Django 3.1.4 on 2021-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('datasn', '0001_initial'), ('datasn', '0002_auto_20210406_0643'), ('datasn', '0003_auto_20210406_0645'), ('datasn', '0004_auto_20210406_0657'), ('datasn', '0005_auto_20210406_0703')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasnCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('parttype', models.CharField(max_length=7, verbose_name='PartType')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('engines_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='EnginesUrl')),
            ],
            options={
                'verbose_name': 'Datasn Category',
                'verbose_name_plural': 'Datasn Categories',
            },
        ),
        migrations.CreateModel(
            name='DatasnMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Datasn Make',
                'verbose_name_plural': 'Datasn Make',
            },
        ),
        migrations.CreateModel(
            name='DatasnYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('model_url', models.CharField(max_length=1000, verbose_name='ModelUrl')),
                ('make', models.ManyToManyField(blank=True, null=True, related_name='year', to='datasn.DatasnMake', verbose_name='Make')),
            ],
            options={
                'verbose_name': 'Datasn Year',
                'verbose_name_plural': 'Datasn Years',
                'unique_together': {('title', 'model_url')},
            },
        ),
    ]
